[build]
  base    = "landing"
  command = "npm run build"
  publish = "landing/dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
